"""Public ORM model exports."""

from study_agent.infrastructure.db.models.answers import (
    AnswerDependencyModel,
    ConversationMessageModel,
    ConversationModel,
    LearnerMemoryModel,
    QueryEventModel,
    QueryRunModel,
    RetrievalSnapshotModel,
)
from study_agent.infrastructure.db.models.auth import (
    AccountModel,
    AccountSessionModel,
    RegistrationInvitationModel,
)
from study_agent.infrastructure.db.models.core import (
    CourseModel,
    DeletionJobModel,
    DocumentModel,
    DocumentRevisionModel,
    IdempotencyRecordModel,
    OutboxEventModel,
    StoredObjectModel,
    UploadSessionModel,
    UserModel,
)
from study_agent.infrastructure.db.models.ingestion import (
    ParseAttemptResultModel,
    RevisionAssetModel,
    RevisionBlockModel,
    RevisionChunkModel,
    RevisionPageModel,
)
from study_agent.infrastructure.db.models.jobs import (
    JobArtifactModel,
    JobEventModel,
    PageCheckpointModel,
    ParseJobModel,
)
from study_agent.infrastructure.db.models.learning import (
    LearningMasteryModel,
    LearningUnitModel,
    LearningUnitSourceModel,
    PracticeAttemptModel,
    PracticeBatchAttemptModel,
    PracticeBatchEventModel,
    PracticeBatchItemModel,
    PracticeBatchModel,
    PracticeQuestionEvidenceModel,
    PracticeQuestionModel,
    PracticeSessionModel,
    PracticeSessionQuestionModel,
)
from study_agent.infrastructure.db.models.note_versions import (
    NoteContentVersionModel,
    NoteSourceStateOverlayModel,
    NoteVersionCoverageModel,
    NoteVersionCoverageUnitModel,
    NoteVersionSourceLinkModel,
    NoteVersionSourcePayloadModel,
    NoteVersionSourceSnapshotModel,
)
from study_agent.infrastructure.db.models.note_workflow import (
    NoteCommandDedupModel,
    NoteCoverageUnitModel,
    NoteCoverageUnitResultModel,
    NoteGenerationAttemptModel,
    NoteGenerationBatchModel,
    NoteGenerationEventModel,
    NoteGenerationInputModel,
    NoteGenerationItemModel,
    NoteGenerationOutputModel,
    NoteItemInputModel,
)
from study_agent.infrastructure.db.models.notes import NoteModel, NoteSourceModel
from study_agent.infrastructure.db.models.retrieval import (
    ChunkEmbeddingModel,
    EmbeddingModelModel,
    IndexJobModel,
    LexicalManifestModel,
    RetrievalTraceModel,
)

ChunkModel = RevisionChunkModel

__all__ = [
    "AccountModel",
    "AccountSessionModel",
    "AnswerDependencyModel",
    "ChunkEmbeddingModel",
    "ChunkModel",
    "ConversationMessageModel",
    "ConversationModel",
    "CourseModel",
    "DeletionJobModel",
    "DocumentModel",
    "DocumentRevisionModel",
    "EmbeddingModelModel",
    "IdempotencyRecordModel",
    "IndexJobModel",
    "JobArtifactModel",
    "JobEventModel",
    "LearnerMemoryModel",
    "LearningMasteryModel",
    "LearningUnitModel",
    "LearningUnitSourceModel",
    "LexicalManifestModel",
    "NoteCommandDedupModel",
    "NoteContentVersionModel",
    "NoteCoverageUnitModel",
    "NoteCoverageUnitResultModel",
    "NoteGenerationAttemptModel",
    "NoteGenerationBatchModel",
    "NoteGenerationEventModel",
    "NoteGenerationInputModel",
    "NoteGenerationItemModel",
    "NoteGenerationOutputModel",
    "NoteItemInputModel",
    "NoteModel",
    "NoteSourceModel",
    "NoteSourceStateOverlayModel",
    "NoteVersionCoverageModel",
    "NoteVersionCoverageUnitModel",
    "NoteVersionSourceLinkModel",
    "NoteVersionSourcePayloadModel",
    "NoteVersionSourceSnapshotModel",
    "OutboxEventModel",
    "PageCheckpointModel",
    "ParseAttemptResultModel",
    "ParseJobModel",
    "PracticeAttemptModel",
    "PracticeBatchAttemptModel",
    "PracticeBatchEventModel",
    "PracticeBatchItemModel",
    "PracticeBatchModel",
    "PracticeQuestionEvidenceModel",
    "PracticeQuestionModel",
    "PracticeSessionModel",
    "PracticeSessionQuestionModel",
    "QueryEventModel",
    "QueryRunModel",
    "RegistrationInvitationModel",
    "RetrievalSnapshotModel",
    "RetrievalTraceModel",
    "RevisionAssetModel",
    "RevisionBlockModel",
    "RevisionChunkModel",
    "RevisionPageModel",
    "StoredObjectModel",
    "UploadSessionModel",
    "UserModel",
]
