"""Stable contracts shared by the API and local worker."""

from study_contracts.answers import AnswerStatus, Citation, Claim, Refusal, StructuredAnswer
from study_contracts.canonical import canonical_json_bytes, canonical_sha256
from study_contracts.chunks import Chunk
from study_contracts.documents import (
    PARSE_ATTEMPT_MEDIA_TYPE,
    PARSE_PAGE_MEDIA_TYPE,
    PARSER_RAW_MEDIA_TYPE,
    Asset,
    AssetType,
    Block,
    BlockType,
    BoundingBox,
    Page,
    PageIssue,
    PageIssueSeverity,
    PageQuality,
    PageQualityStatus,
    ParseAttemptResult,
    ParseResultBundle,
    ParseResultManifest,
    SourceLocator,
)
from study_contracts.evidence import Evidence
from study_contracts.jobs import (
    JobArtifactReceipt,
    JobClaimRequest,
    JobClaimResponse,
    JobCompleteRequest,
    JobEventEnvelope,
    JobFailRequest,
    JobHeartbeatRequest,
    JobProgress,
    JobSnapshot,
    JobStartRequest,
    JobStatus,
    LeaseCommand,
    PageCheckpointRequest,
    WorkerCapabilities,
    WorkerLease,
)
from study_contracts.notes import Note, NoteSource

__all__ = [
    "PARSER_RAW_MEDIA_TYPE",
    "PARSE_ATTEMPT_MEDIA_TYPE",
    "PARSE_PAGE_MEDIA_TYPE",
    "AnswerStatus",
    "Asset",
    "AssetType",
    "Block",
    "BlockType",
    "BoundingBox",
    "Chunk",
    "Citation",
    "Claim",
    "Evidence",
    "JobArtifactReceipt",
    "JobClaimRequest",
    "JobClaimResponse",
    "JobCompleteRequest",
    "JobEventEnvelope",
    "JobFailRequest",
    "JobHeartbeatRequest",
    "JobProgress",
    "JobSnapshot",
    "JobStartRequest",
    "JobStatus",
    "LeaseCommand",
    "Note",
    "NoteSource",
    "Page",
    "PageCheckpointRequest",
    "PageIssue",
    "PageIssueSeverity",
    "PageQuality",
    "PageQualityStatus",
    "ParseAttemptResult",
    "ParseResultBundle",
    "ParseResultManifest",
    "Refusal",
    "SourceLocator",
    "StructuredAnswer",
    "WorkerCapabilities",
    "WorkerLease",
    "canonical_json_bytes",
    "canonical_sha256",
]
